apiVersion: apps/v1
kind: Deployment
metadata:
  name: $(APP_NAME)
  namespace: $(NAMESPACE)
spec:
  replicas: $(REPLICAS)
  selector:
    matchLabels:
      app: $(APP_NAME)
  template:
    metadata:
      labels:
        app: $(APP_NAME)
    spec:
      containers:
      - name: $(APP_NAME)
        image: $(IMAGE)
        ports:
        - containerPort: $(SERVICE_PORT)
        resources:
          requests:
            cpu: $(REQ_CPU)
            memory: $(REQ_MEM)
          limits:
            cpu: $(LIM_CPU)
            memory: $(LIM_MEM)

