varReference:
  - path: metadata/name
  - path: metadata/namespace

  - path: spec/selector/matchLabels/app
  - path: spec/template/metadata/labels/app

  - path: spec/template/spec/containers/name
  - path: spec/template/spec/containers/image

  - path: spec/template/spec/containers/resources/requests/cpu
  - path: spec/template/spec/containers/resources/requests/memory
  - path: spec/template/spec/containers/resources/limits/cpu
  - path: spec/template/spec/containers/resources/limits/memory

  - path: spec/template/spec/containers/readinessProbe/httpGet/path
  - path: spec/template/spec/containers/livenessProbe/httpGet/path

  - path: spec/selector/app
